; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[admin_menu][version] = "3.0-rc4"

projects[backup_migrate][version] = "2.8"

projects[block_class][version] = "2.1"

projects[breakpoints][version] = "1.1"

projects[ctools][version] = "1.3+4-dev"

projects[context][version] = "3.1"

projects[context_omega][version] = "1.1"

projects[ds][version] = "2.6"

projects[entity][version] = "1.2"

projects[entity_view_mode][version] = "1.0-rc1"

projects[features][version] = "2.0"

projects[fieldable_panels_panes][version] = "1.5"

projects[picture][version] = "1.1"

projects[jquery_update][version] = "2.3"

projects[panelizer][version] = "3.1+2-dev"

projects[panels][version] = "3.3"

projects[panels_everywhere][version] = "1.0-rc1"

projects[responsive_menus][version] = "1.3"

projects[views][version] = "3.7"

; Themes

projects[omega][version] = "4.1"



